### PR TITLE
filtering functions by product type completed

### PR DESCRIPTION
**Pull request by jamierashley**
### What is a quick description of the change?
Filtering by product type finished up. There are different functions for each product type because the ID needed to be unique...I know there is a way that it can be done without it being unique but more research is needed on it.

### Screenshot/Screengrab after this change?

Screenshot 2020-06-29 at 7 11 24 PM

Screenshot 2020-06-29 at 7 11 30 PM

### Is this fixing an issue?

none

### Are there more details that are relevant?

The products array still isn't working...not sure why. I tested these functions in fiddle.net with the json array hardcoded so the functions work as of now.

### Any additional comments?

The output of the functions is open to be changed of course but for clarity they return this way. Filters for tags and pricing are on the way. Also working on having products disappear when box is unchecked. As of now once checked initially the data remains on the screen.

### CODE REVIEW

**Comment by jamierashley** [comment]
the "merge branch 'master' into filtering" came when I resolved merge conflicts from my previous PR not my initial commit

**Comment by LilCSharp** [comment]
I would suggest a different approach for going about the filtering. What you have now is fine, but as more and more categories pile up, it will make your code unwieldy. It also seems to me like you are loading all of the products into one big array, and then selecting what fits the specified qualities. This is pretty inefficient. I would recommend having each quality represent a string. If a checkbox is selected, then that string will be included in a query string that you can send to the API to only get the products that you need.

**Comment by jamierashley** [comment]
@googlebot I fixed it.

**Comment by aliciasimon** [comment]
If what you have now works, then that's fine for the time being. I'm thinking about your issue, and I agree with you that there has to be another way. What I'm having trouble with is the getElementsById(). Like you said, each id has to be unique... I don't know if this is applicable but maybe you can do var x = getElementsByClass(some generic name "product-type") and then x.name to access the type of product (ex. "lipstick") etc.? I'm really not sure about this approach, but Caleb's approach sounds good.

**Pull request closed without merging**
